spring:
  thymeleaf:
    suffix: .xhtml
    prefix: classpath:/templates/
    mode: HTML
    encoding: UTF-8
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/core
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    root: DEBUG
jakarta:
  persistence:
    jdbc:
      url: jdbc:mysql://localhost:3306/core